name: simple_json
description: Simple way to dynamically convert from and to JSON using build-time generators given a type.
version: 2.1.1
homepage: https://github.com/FlutterDevTools/simple_json/tree/master/simple_json

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  simple_json_mapper: ^2.1.0
  build_resolvers: ^2.0.3
  analyzer: ^1.7.1
  build: ^2.0.2
  source_gen: ^1.0.2
  path: ^1.8.0
  glob: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.8
  build_runner: ^2.0.4
