name: simple_json_example
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  simple_json_mapper: ^2.1.0
  uuid: ^3.0.1

dependency_overrides:
  simple_json_mapper:
    path: ../simple_json_mapper

dev_dependencies:
  build_runner: ^1.12.2
  build_verify: ^2.0.0
  test: ^1.16.8
  simple_json:
    path: ../simple_json
