name: simple_json_example

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_json_mapper: ^0.1.6
  uuid: ^2.1.0

dependency_overrides:
  simple_json_mapper:
    path: ../simple_json_mapper

dev_dependencies:
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  test: ^1.14.7
  simple_json:
    path: ../simple_json
