name: simple_json_example
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  simple_json_mapper: ^2.2.0
  uuid: ^3.0.4

dependency_overrides:
  simple_json_mapper:
    path: ../simple_json_mapper

dev_dependencies:
  build_runner: ^2.1.2
  build_verify: ^2.0.0
  test: ^1.17.12
  simple_json:
    path: ../simple_json
