name: simple_json_example

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_json_mapper: ^0.1.0

dev_dependencies:
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  simple_json:
    path: ../simple_json
  test: ^1.14.7
