name: simple_json_mapper
description: >-
  Classes and helper functions that support JSON code generation and serialization via the
  `simple_json` package.
version: 0.1.0
homepage: https://github.com/FlutterDevTools/simple_json

environment:
  sdk: ">=2.7.0 <3.0.0"

