name: simple_json_mapper
description: >-
  Classes and helper functions that support JSON code generation and serialization via the
  `simple_json` package.
version: 2.2.0
homepage: https://github.com/FlutterDevTools/simple_json

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
