name: simple_json_example
description: simple_json example project
version: 0.1.0
homepage: https://github.com/FlutterDevTools/simple_json

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  simple_json_mapper: ^0.3.0
  simple_json:
    path: ../

dependency_overrides:
  simple_json_mapper:
    path: ../../simple_json_mapper

dev_dependencies:
  build_runner: ^1.10.0
